### ISSUE TITLE
Not a supported wheel on this platform (macOS High Sierra)

### ISSUE THREAD

**Issue by HassanSE** [lakshayg/tensorflow-build-archived#19]
Trying [this](https://github.com/lakshayg/tensorflow-build/blob/master/tensorflow-1.4.1-cp36-cp36m-macosx_10_13_x86_64.whl) on macOS High Sierra but getting this error:

> tensorflow-1.4.1-cp36-cp36m-macosx_10_13_x86_64.whl is not a supported wheel on this platform.

**Comment by lakshayg** [comment]
Do the macOS and python version match the versions in the binary's name?

**Comment by HassanSE** [comment]
Yes, macOS is `10.13.2` and Python is `3.6.4`

**Comment by lakshayg** [comment]
@frankhinek there seems to be an issue with the binary you contributed. Could you please help one of our users?

**Comment by frankhinek** [comment]
Happy to, @lakshayg.  I'll test it out as soon as I get back in front of my 10.13 system.

**Comment by lakshayg** [comment]
Thanks a lot Frank.

This is why I love open-source, lots of helpful people.

**Comment by frankhinek** [comment]
@HassanSE, can you let us know what the result of this test is?

```python
>>> import pip
>>> tags = pip.pep425tags.get_supported()
>>> ('cp36', 'cp36m', 'macosx_10_13_x86_64') in tags
```

The output should be either `True` or `False`.
 
Can you also send the output of:

```python
>>> pip.pep425tags.get_impl_ver()
>>> pip.pep425tags.get_abi_tag()
>>> pip.pep425tags.get_platform()
```

Thanks!

**Comment by HassanSE** [comment]
Here's the output:

`True`
`36`
`cp36m`
`macosx_10_13_x86_64`

**Comment by frankhinek** [comment]
That is quite strange.  It should work.  I'll try to do some further testing when I get off work.

**Comment by frankhinek** [comment]
@HassanSE I can't see any reason why it doesn't work on your system.

I've tried reinstalling under a new environment on my macOS 10.13.2 (17C88) system and had no issues.  I've also had someone else install on their High Sierra MacBook, and it worked fine as well.

Are you using virtualenvs, Anaconda/Miniconda, or something similar to keep your system python isolated?

**Comment by HassanSE** [comment]
Alright. I was just trying to remove a warning that I was getting when running any Python program which is:

`/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)`

For the time being, I will ignore it.

**Comment by lakshayg** [comment]
Let's leave this issue open. Someone who stumbles upon the repo might be able to help. I will add a help-wanted label.

**Comment by frankhinek** [comment]
Turns out it is a known TensorFlow issue with the 1.4 release: https://github.com/tensorflow/tensorflow/issues/14182

It has been fixed in nightly builds but won't be included in an official release until 1.5.x.  For now, it'll work with 1.4.1--you'll just see the warning message.  Alternatively, just use Python 3.5 and TF 1.4.1.

@HassanSE - On a separate, but related note, I'd highly recommend looking into virtualenvs, conda environments, or something equivalent.  If Python is running from `/Library/Frameworks/Python.framework/` this likely means you installed using the installer off python.org.  I've seen people have all sorts of issues trying to co-mingle packages (esp. custom compiled versions) in a single Python install.  Life is much easier when you run various projects along with their package dependencies from separate environments.

**Comment by HassanSE** [comment]
That's true, I've installed Python using installer from python.org. It would be helpful for me if you could explain

> Life is much easier when you run various projects along with their package dependencies from separate environments.

Thanks :)

**Comment by frankhinek** [comment]
@HassanSE A search for "Why use virtualenv?" or "Why use conda?" will yield you many sources of information but here's are a few links to get you started.  Happy coding!

* https://www.davidfischer.name/2010/04/why-you-should-be-using-pip-and-virtualenv/
* https://jakevdp.github.io/blog/2016/08/25/conda-myths-and-misconceptions/
* http://docs.python-guide.org/en/latest/dev/virtualenvs/
* https://pythontips.com/2013/07/30/what-is-virtualenv/

**Comment by yanshengjia** [comment]
Met the same problem.

**Comment by frankhinek** [comment]
@yanshengjia You didn't mention which problem you are running into -- there were a couple discussed in this thread.  If you having issues with "wheel not supported" you need to be using virtualenvs, conda, py_env or something similar.  If you are trying to install multiple copies into the system directories you are going to have issues.

If you are running into the "does not match runtime version 3.6" issue, this is a TensorFlow bug that won't be fixed until 1.5 is released.  Read through the thread to see what your options are.

**Comment by yanshengjia** [comment]
@frankhinek Thank you for your advice.

I met
`tensorflow-1.4.1-cp36-cp36m-macosx_10_13_x86_64.whl is not a supported wheel on this platform.`

I will give virtualenv a try.

**Comment by frankhinek** [comment]
You are running macOS 10.13 right?

**Comment by yanshengjia** [comment]
Yeah, macOS 10.13.2

**Comment by S-Retr0** [comment]
I had the same problem.
Running:
- ``pip install --ignore-installed --upgrade /Users/userName/Downloads/tensorflow-1.8.0-cp36-cp36m-macosx_10_7_x86_64.whl``

Gave me the following error:
- `tensorflow-1.8.0-cp36-cp36m-macosx_10_7_x86_64.whl is not a supported wheel on this platform.`

To solve it I used pip3 and python3 (installed with [Homebrew](https://brew.sh/)) since pip was pointing to python 2.7

Now just run it with pip3 and it should work perfectly.
- `pip3 install --ignore-installed --upgrade /Users/userName/Downloads/tensorflow-1.8.0-cp36-cp36m-macosx_10_7_x86_64.whl`


To check it type:
- `python3`
- `>>> import tensorflow as tf`
- `>>> hello = tf.constant('Hello, TensorFlow!')`
- `>>> sess = tf.Session()`
- `>>> print(sess.run(hello))`
You should get an output like this:
`b'Hello, TensorFlow!'`

Hope it helped

**Comment by qiugen** [comment]
i had the same problem in virtualenv, 
tensorflow version(1.8.0)
macos high sierra, 10.13.4, X86_64, python27 
`tensorflow-1.8.0-cp36-cp36m-macosx_10_7_x86_64.whl is not a supported wheel on this platform.`

**Comment by lakshayg** [comment]
@qiugen You are probably getting this issue because you are using the binary for python3 (notice "cp36-cp36m" in the binary name) and trying to install it with python2.

I have uploaded new binaries for TF 1.8.0 on macOS. Please give them a try and see if they solve your issue. Here are the links
Python 2.7.15 - [Download](https://github.com/lakshayg/tensorflow-build/releases/download/v1.8.0-macos-py27-py36-avx-avx2-fma-sse41-sse42/tensorflow-1.8.0-cp27-cp27m-macosx_10_13_x86_64.whl)
Python 3.6.5 - [Download](https://github.com/lakshayg/tensorflow-build/releases/download/v1.8.0-macos-py27-py36-avx-avx2-fma-sse41-sse42/tensorflow-1.8.0-cp36-cp36m-macosx_10_13_x86_64.whl)

**Comment by lakshayg** [comment]
I am closing this issue since it refers to a very old version of TF. Feel free to reopen if you still encounter this problem.
